version: 2

project_name: hydra

before:
  hooks:
    - go mod tidy

builds:
  - id: hydra
    main: ./cmd/client
    binary: hydra
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - "-s -w -X github.com/khabib-developer/hydra/internal/version.version={{.Version}}"

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

nfpms:
  - id: hydra
    package_name: hydra
    formats: [deb, rpm]
    maintainer: "Khabib Developer <your@email>"
    license: MIT
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - name: hydra
    repository:
      owner: khabib-developer
      name: homebrew-tap
    commit_author:
      name: khabib-developer
      email: habibsharopov501@gmail.com
    description: "Hydra — cross-platform chat and file sharing app"
    homepage: "https://github.com/khabib-developer/hydra"
    license: "MIT"
    install: |
      bin.install "hydra"
